version: '3.9'
services:
    nginx:
        image: ghcr.io/u-sb/nginx
        hostname: nginx
        ports:
            - '80:80'
            - '443:443'
        container_name: nginx
        restart: always
        volumes:
            - ./nginx-config:/usr/src/docker-nginx/conf
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
