services:
    nginx:
        image: ghcr.io/u-sb/nginx
        hostname: nginx
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
        container_name: nginx
        restart: always
        volumes:
            - ./nginx-config:/usr/src/docker-nginx/conf
        # command:
        #     - default.conf
        #     - options/websocket.conf
        #     - contoso.example.conf
        logging:
            driver: "json-file"
            options:
                max-size: "10m"

# networks:
#   gateway:
#     name: nginx-gateway
