name: Docker Build

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag "$IMAGE_NAME"

      - name: Push image
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"
          IMAGE_VERSION="${GITHUB_REF##*/v}"
          curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
          docker-slim build --http-probe=false "$IMAGE_NAME"
          docker run --rm "$IMAGE_NAME.slim" sh -c "nginx -V && nginx -t"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:$IMAGE_VERSION"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:latest"
          docker tag "$IMAGE_NAME.slim" "$IMAGE_ID:$IMAGE_VERSION-slim"
          docker tag "$IMAGE_NAME.slim" "$IMAGE_ID:slim"
          docker push "$IMAGE_ID:$IMAGE_VERSION-slim"
          docker push "$IMAGE_ID:slim"
          docker push "$IMAGE_ID:$IMAGE_VERSION"
          docker push "$IMAGE_ID:latest"
