name: Docker Build

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: nginx

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set version tag
        run: echo "IMAGE_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./Dockerfile
          tags: |
            "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"
            "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
